name: .NET CI for Task08

on:
  push:
    branches: [task08]
  pull_request:
    branches: [task08]

jobs:
  build-and-test-task08:
    runs-on: windows-latest
    env:
      SOLUTION_NAME: practice2025.sln
      MAIN_PROJECT: task08/task08.csproj
      TEST_PROJECT: task08tests/task08tests.csproj

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x

    - name: Cache NuGet packages
      uses: actions/cache@v3
      with:
        path: |
          ~/.nuget/packages
          **/bin
          **/obj
        key: ${{ runner.os }}-nuget-task08-${{ hashFiles('**/task08/*.csproj', '**/task08tests/*.csproj') }}
        restore-keys: |
          ${{ runner.os }}-nuget-task08-
      
    - name: Restore dependencies
      run: dotnet restore ${{ env.SOLUTION_NAME }}
      
    - name: Build main project
      run: dotnet build ${{ env.MAIN_PROJECT }} --configuration Release --no-restore
      
    - name: Build test project
      run: dotnet build ${{ env.TEST_PROJECT }} --configuration Release --no-restore
      
    - name: Run tests
      run: dotnet test ${{ env.TEST_PROJECT }} --configuration Release --no-build --logger "trx;LogFileName=test-results.xml"
      
    - name: Publish test results
      uses: actions/upload-artifact@v3
      if: always()
      with:
        name: task08-test-results
        path: ${{ env.TEST_PROJECT }}/TestResults/*.trx

    - name: Code coverage report
      run: |
        dotnet test ${{ env.TEST_PROJECT }} --collect:"XPlat Code Coverage" --settings coverlet.runsettings
        reportgenerator -reports:${{ env.TEST_PROJECT }}/TestResults/**/coverage.cobertura.xml -targetdir:coveragereport -reporttypes:HtmlInline_AzurePipelines
      continue-on-error: true